# ---- USERS ----
### get all users
GET http://localhost:4000/users
### post
POST http://localhost:4000/users
Content-Type: application/json

{
"username":"norman",
"password":"password123"
}

### patch
PATCH HTTP://localhost:4000/users/65536bf7c5ea12a764ef1c46
Content-Type: application/json

{"password":"fake"}

# ---- NOTES ----
###
GET HTTP://localhost:4000/notes
###
GET HTTP://localhost:4000/notes/norman

### post
POST http://localhost:4000/notes
Content-Type: application/json

{
"username":"norman"
}

### patch
PATCH HTTP://localhost:4000/notes/norman
Content-Type: application/json

{"username":"dave"}
### delete id
DELETE  HTTP://localhost:4000/notes/
Content-Type: application/json

{"id":"65537f85c7ba3a926b9a00eb"}
